# Set webook
POST https://api.telegram.org/bot{{telegram_bot_token}}/setWebhook
Content-Type: application/x-www-form-urlencoded

url=https://us-east1-conditions-450312.cloudfunctions.net/botWebhook

###
# Get BRA
GET https://public-api.meteofrance.fr/public/DPBRA/massif/BRA?id-massif=3&format=xml
Content-Type: application/xml
apiKey: {{meteofrance_api_key}}

###
# List massifs
GET https://public-api.meteofrance.fr/public/DPBRA/v1/liste-massifs
accept: */*
Authorization: Bearer {{meteofrance_api_key}}

###
# Trigger Cron Job
# Note: Requires gcloud authentication token
# Get token with: gcloud auth print-identity-token
POST https://cron-dmytevhowa-ue.a.run.app
Authorization: Bearer {{gcloud_identity_token}}