version: "3"

includes:
  infra: ./infra
  functions: ./functions

tasks:
  deploy:
    desc: Deploy
    cmds:
      - task: functions:build
      - task: infra:apply

  plan:
    desc: Plan
    cmds:
      - task: infra:plan

  trigger-cron:
    desc: Trigger the cron function manually
    cmds:
      - gcloud scheduler jobs run cron-job-trigger-hourly --location=europe-west1